[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "4f76bf66d48941ef91a5b7da05dace9121340412"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "1441f1e3157ebff490cb324fd1aef13b7d583092990eba2724a8bd0ee3f040fe"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "740015aee1917c72978d3191acd8dde776479597"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "f5758fcaa506ca72bfcd9d47435b0bb068fb809282c5f54c9a3eb7f68875b6e3"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "9a4863fc842eb77fff5d36d661a17071928a3417"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "9fce7ea75b6564bf551d7795aaf80d7a75d408f08ace4c33fe3c22a8b1217402"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "a59fdd355b6019271772506cb9d4820f2aa492d0"
os = "freebsd"

    [[GAP_pkg_anupq.download]]
    sha256 = "d19f8be4e017aa02ebb034b632d9b2f3c50ec6afdeea2d43b1e1a46526bf064c"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_anupq]]
arch = "powerpc64le"
git-tree-sha1 = "bd69d9c9a6e911e4a6f483913be9fbd521bf265c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "711ba7eddd4a5c5f2df130b79f9851177bacb010fc2df91abbc95aa4ecc54dba"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "riscv64"
git-tree-sha1 = "eddf7ec60df1b23e9fb519474cd0c56d05fa7b74"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "da7e32d051194d2034cb7851b0f8a1bb2a6bad1a25dd889b827dfd6be5ea0fc8"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "6cafe30260e6db1533147305a3de5120305ddc14"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "993775c6d4262c59c646cbd8c569c8e5808cea46b9fa5668c52ae8b90f2e59e0"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "b25197b71c608426bdb12660231a57c7cd577e63"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "6aa065b60d8621bd85cd6977947396acbd37581e3857fd4ae80c6264bc6d0635"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "2f4dd5f528ab215bc3e91ed637e546c8d158ce63"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "d6b7c92014cd9ad870fe0707cb5a47f0b28ba5f728eaa8330bd327856e1c4426"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "35f479cfb55a5bf6dc2d492a7067e22f33fbbe2c"
os = "freebsd"

    [[GAP_pkg_anupq.download]]
    sha256 = "73109c4a1a661df21df31a078b738871b458ce2ff7185a48ac85e4b12e5cb645"
    url = "https://github.com/lgoettgens/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v301.30200.0+0/GAP_pkg_anupq.v301.30200.0.x86_64-unknown-freebsd.tar.gz"
